apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dex-k8s-authenticator.fullname" . }}
  labels:
    app: {{ template "dex-k8s-authenticator.fullname" . }}
    env: {{ default "dev" .Values.global.deployEnv }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.yaml: |-
    {{- with .Values.dexK8sAuthenticator }}
    listen: http://0.0.0.0:{{ default "5555" .port }}
    debug: {{ default "false" .debug }}
    {{- if .base_path }}
    base_path: {{ .base_path }}
    {{- end }}
    {{- if .logoUrl }}
    logo_uri: {{ .logoUrl }}
    {{- end }}
    {{- if and .tlsCert .tlsKey }}
    tls_cert: "{{ .tlsCert }}"
    tls_key: "{{ .tlsKey }}"
    {{- end }}
    clusters:
{{ toYaml .clusters | indent 4 }}
    {{- end }}
